name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Render Apps
       run: |
  echo "===== $(date) ====="

  echo "Virtual Assistant:"
  curl -o /dev/null -s -w "Status: %{http_code}\n" https://virtualassistant-wxxq.onrender.com

  echo "PulseTalk:"
  curl -o /dev/null -s -w "Status: %{http_code}\n" https://pulsetalk-6lrk.onrender.com/

  echo "Ecommerce Backend:"
  curl -o /dev/null -s -w "Status: %{http_code}\n" https://ecommersebackendshreyash.onrender.com/
